# Generated by Django 4.1 on 2022-08-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="NO NAME", max_length=40, null=True
                    ),
                ),
                (
                    "job_title",
                    models.IntegerField(
                        choices=[
                            (1, "Software developer"),
                            (2, "Data scientist"),
                            (3, "DevOps"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[("AMZN", "AMAZON"), ("GOOGLE", "GOOGLE")], max_length=6
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.department",
                    ),
                ),
            ],
            options={"ordering": ("company", "first_name"),},
        ),
        migrations.CreateModel(
            name="TestAgain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("second_try", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("employees", models.ManyToManyField(to="employees.employee")),
            ],
        ),
    ]
